#syncBack.sh in /Users/agrummer/cernbox/www/bmumu/IsoVarROCs
# rsync --dry-run -avzC --delete --include '*/' --include='err.txt' --include='out.txt' --exclude="*" $USER@lxplus.cern.ch:/afs/cern.ch/user/a/agrummer/WorkSpace/IsoVarROCs/ /Users/agrummer/cernbox/www/bmumu/IsoVarROCs/v8IsoScripts/test/
rsync -avzC --include 'mixVars_*/' --include 'newVarComps/' --include 'newVarCompsMuM/' --include 'newVarCompsMuP/' --include 'oldVars_v7_repeated/' --include='err.txt' --include='out.txt' --exclude="*" $USER@lxplus.cern.ch:/afs/cern.ch/user/a/agrummer/WorkSpace/IsoVarROCs/v8IsoScripts/ /Users/agrummer/Desktop/Bmumu/Bmumu2019/IsoFigures/2020Mar18/v8IsoScripts/
rsync -avzC --include 'mixVars_*/' --include='err.txt' --include='out.txt' --exclude="*" $USER@lxplus.cern.ch:/afs/cern.ch/user/a/agrummer/WorkSpace/IsoVarROCs/v8IsoScriptsIntersect/ /Users/agrummer/Desktop/Bmumu/Bmumu2019/IsoFigures/2020Mar18/v8IsoScriptsIntersect/
# rsync --dry-run -avzC --include 'mixVars_*/' --include='err.txt' --include='out.txt' --exclude="*" $USER@lxplus.cern.ch:/afs/cern.ch/user/a/agrummer/WorkSpace/IsoVarROCs/v8IsoScripts/ /Users/agrummer/Desktop/Bmumu/Bmumu2019/IsoFigures/2020Mar18/
# rsync -avz /Users/agrummer/cernbox/www/bmumu/IsoVarROCs $USER@lxplus.cern.ch:/afs/cern.ch/user/a/agrummer/WorkSpace/IsoVarROCs
# cat /Users/agrummer/Desktop/Bmumu/Bmumu2019/IsoFigures/2020Mar18/v8IsoScripts/mixVars_1516N/err.txt | grep -e "error" -e "Error" -e "ERROR"
echo "grep Files: mixVars_1516AD"
cat /Users/agrummer/Desktop/Bmumu/Bmumu2019/IsoFigures/2020Mar18/v8IsoScripts/mixVars_1516AD/err.txt | grep -e "error" -e "Error" -e "ERROR"
cat /Users/agrummer/Desktop/Bmumu/Bmumu2019/IsoFigures/2020Mar18/v8IsoScripts/mixVars_1516AD/out.txt | grep -e "error" -e "Error" -e "ERROR"
echo "grep Files: mixVars_1516D"
cat /Users/agrummer/Desktop/Bmumu/Bmumu2019/IsoFigures/2020Mar18/v8IsoScripts/mixVars_1516D/err.txt | grep -e "error" -e "Error" -e "ERROR"
cat /Users/agrummer/Desktop/Bmumu/Bmumu2019/IsoFigures/2020Mar18/v8IsoScripts/mixVars_1516D/out.txt | grep -e "error" -e "Error" -e "ERROR"
# cat /Users/agrummer/Desktop/Bmumu/Bmumu2019/IsoFigures/2020Mar18/v8IsoScripts/mixVars_1516AN/err.txt | grep -e "error" -e "Error" -e "ERROR"
# cat /Users/agrummer/Desktop/Bmumu/Bmumu2019/IsoFigures/2020Mar18/v8IsoScripts/mixVars_1516AN/out.txt | grep -e "error" -e "Error" -e "ERROR"
echo "grep Files: mixVars_customD"
cat /Users/agrummer/Desktop/Bmumu/Bmumu2019/IsoFigures/2020Mar18/v8IsoScripts/mixVars_customD/err.txt | grep -e "error" -e "Error" -e "ERROR"
cat /Users/agrummer/Desktop/Bmumu/Bmumu2019/IsoFigures/2020Mar18/v8IsoScripts/mixVars_customD/out.txt | grep -e "error" -e "Error" -e "ERROR"
echo "grep Files: mixVars_customD1"
cat /Users/agrummer/Desktop/Bmumu/Bmumu2019/IsoFigures/2020Mar18/v8IsoScripts/mixVars_customD1/err.txt | grep -e "error" -e "Error" -e "ERROR"
cat /Users/agrummer/Desktop/Bmumu/Bmumu2019/IsoFigures/2020Mar18/v8IsoScripts/mixVars_customD1/out.txt | grep -e "error" -e "Error" -e "ERROR"
echo "grep Files: mixVars_customD2"
cat /Users/agrummer/Desktop/Bmumu/Bmumu2019/IsoFigures/2020Mar18/v8IsoScripts/mixVars_customD2/err.txt | grep -e "error" -e "Error" -e "ERROR"
cat /Users/agrummer/Desktop/Bmumu/Bmumu2019/IsoFigures/2020Mar18/v8IsoScripts/mixVars_customD2/out.txt | grep -e "error" -e "Error" -e "ERROR"
# cat /Users/agrummer/Desktop/Bmumu/Bmumu2019/IsoFigures/2020Mar18/v8IsoScripts/mixVars_customN/err.txt | grep -e "error" -e "Error" -e "ERROR"
# cat /Users/agrummer/Desktop/Bmumu/Bmumu2019/IsoFigures/2020Mar18/v8IsoScripts/mixVars_customN/out.txt | grep -e "error" -e "Error" -e "ERROR"
echo "grep Files: mixVars_looseD"
cat /Users/agrummer/Desktop/Bmumu/Bmumu2019/IsoFigures/2020Mar18/v8IsoScripts/mixVars_looseD/err.txt | grep -e "error" -e "Error" -e "ERROR"
cat /Users/agrummer/Desktop/Bmumu/Bmumu2019/IsoFigures/2020Mar18/v8IsoScripts/mixVars_looseD/out.txt | grep -e "error" -e "Error" -e "ERROR"
echo "grep Files: mixVars_looseD1"
cat /Users/agrummer/Desktop/Bmumu/Bmumu2019/IsoFigures/2020Mar18/v8IsoScripts/mixVars_looseD1/err.txt | grep -e "error" -e "Error" -e "ERROR"
cat /Users/agrummer/Desktop/Bmumu/Bmumu2019/IsoFigures/2020Mar18/v8IsoScripts/mixVars_looseD1/out.txt | grep -e "error" -e "Error" -e "ERROR"
echo "grep Files: mixVars_looseD2"
cat /Users/agrummer/Desktop/Bmumu/Bmumu2019/IsoFigures/2020Mar18/v8IsoScripts/mixVars_looseD2/err.txt | grep -e "error" -e "Error" -e "ERROR"
cat /Users/agrummer/Desktop/Bmumu/Bmumu2019/IsoFigures/2020Mar18/v8IsoScripts/mixVars_looseD2/out.txt | grep -e "error" -e "Error" -e "ERROR"
# cat /Users/agrummer/Desktop/Bmumu/Bmumu2019/IsoFigures/2020Mar18/v8IsoScripts/mixVars_looseN/err.txt | grep -e "error" -e "Error" -e "ERROR"
# cat /Users/agrummer/Desktop/Bmumu/Bmumu2019/IsoFigures/2020Mar18/v8IsoScripts/mixVars_looseN/out.txt | grep -e "error" -e "Error" -e "ERROR"
echo "grep Files: mixVars_1516N"
cat /Users/agrummer/Desktop/Bmumu/Bmumu2019/IsoFigures/2020Mar18/v8IsoScriptsIntersect/mixVars_1516N/err.txt | grep -e "error" -e "Error" -e "ERROR"
cat /Users/agrummer/Desktop/Bmumu/Bmumu2019/IsoFigures/2020Mar18/v8IsoScriptsIntersect/mixVars_1516N/out.txt | grep -e "error" -e "Error" -e "ERROR"
# cat /Users/agrummer/Desktop/Bmumu/Bmumu2019/IsoFigures/2020Mar18/v8IsoScriptsIntersect/mixVars_1516AD/err.txt | grep -e "error" -e "Error" -e "ERROR"
# cat /Users/agrummer/Desktop/Bmumu/Bmumu2019/IsoFigures/2020Mar18/v8IsoScriptsIntersect/mixVars_1516AD/out.txt | grep -e "error" -e "Error" -e "ERROR"
# cat /Users/agrummer/Desktop/Bmumu/Bmumu2019/IsoFigures/2020Mar18/v8IsoScriptsIntersect/mixVars_1516D/err.txt | grep -e "error" -e "Error" -e "ERROR"
# cat /Users/agrummer/Desktop/Bmumu/Bmumu2019/IsoFigures/2020Mar18/v8IsoScriptsIntersect/mixVars_1516D/out.txt | grep -e "error" -e "Error" -e "ERROR"
echo "grep Files: mixVars_1516AN"
cat /Users/agrummer/Desktop/Bmumu/Bmumu2019/IsoFigures/2020Mar18/v8IsoScriptsIntersect/mixVars_1516AN/err.txt | grep -e "error" -e "Error" -e "ERROR"
cat /Users/agrummer/Desktop/Bmumu/Bmumu2019/IsoFigures/2020Mar18/v8IsoScriptsIntersect/mixVars_1516AN/out.txt | grep -e "error" -e "Error" -e "ERROR"
# cat /Users/agrummer/Desktop/Bmumu/Bmumu2019/IsoFigures/2020Mar18/v8IsoScriptsIntersect/mixVars_customD/err.txt | grep -e "error" -e "Error" -e "ERROR"
# cat /Users/agrummer/Desktop/Bmumu/Bmumu2019/IsoFigures/2020Mar18/v8IsoScriptsIntersect/mixVars_customD/out.txt | grep -e "error" -e "Error" -e "ERROR"
echo "grep Files: mixVars_customN"
cat /Users/agrummer/Desktop/Bmumu/Bmumu2019/IsoFigures/2020Mar18/v8IsoScriptsIntersect/mixVars_customN/err.txt | grep -e "error" -e "Error" -e "ERROR"
cat /Users/agrummer/Desktop/Bmumu/Bmumu2019/IsoFigures/2020Mar18/v8IsoScriptsIntersect/mixVars_customN/out.txt | grep -e "error" -e "Error" -e "ERROR"
# cat /Users/agrummer/Desktop/Bmumu/Bmumu2019/IsoFigures/2020Mar18/v8IsoScriptsIntersect/mixVars_looseD/err.txt | grep -e "error" -e "Error" -e "ERROR"
# cat /Users/agrummer/Desktop/Bmumu/Bmumu2019/IsoFigures/2020Mar18/v8IsoScriptsIntersect/mixVars_looseD/out.txt | grep -e "error" -e "Error" -e "ERROR"
echo "grep Files: mixVars_looseN"
cat /Users/agrummer/Desktop/Bmumu/Bmumu2019/IsoFigures/2020Mar18/v8IsoScriptsIntersect/mixVars_looseN/err.txt | grep -e "error" -e "Error" -e "ERROR"
cat /Users/agrummer/Desktop/Bmumu/Bmumu2019/IsoFigures/2020Mar18/v8IsoScriptsIntersect/mixVars_looseN/out.txt | grep -e "error" -e "Error" -e "ERROR"
echo "grep Files: newVars"
cat /Users/agrummer/Desktop/Bmumu/Bmumu2019/IsoFigures/2020Mar18/v8IsoScripts/newVarComps/err.txt | grep -e "error" -e "Error" -e "ERROR"
cat /Users/agrummer/Desktop/Bmumu/Bmumu2019/IsoFigures/2020Mar18/v8IsoScripts/newVarComps/out.txt | grep -e "error" -e "Error" -e "ERROR"
echo "grep Files: oldVars"
cat /Users/agrummer/Desktop/Bmumu/Bmumu2019/IsoFigures/2020Mar18/v8IsoScripts/oldVars_v7_repeated/err.txt | grep -e "error" -e "Error" -e "ERROR"
cat /Users/agrummer/Desktop/Bmumu/Bmumu2019/IsoFigures/2020Mar18/v8IsoScripts/oldVars_v7_repeated/out.txt | grep -e "error" -e "Error" -e "ERROR"
echo "grep Files: newVarsMuM"
cat /Users/agrummer/Desktop/Bmumu/Bmumu2019/IsoFigures/2020Mar18/v8IsoScripts/newVarCompsMuM/err.txt | grep -e "error" -e "Error" -e "ERROR"
cat /Users/agrummer/Desktop/Bmumu/Bmumu2019/IsoFigures/2020Mar18/v8IsoScripts/newVarCompsMuM/out.txt | grep -e "error" -e "Error" -e "ERROR"
echo "grep Files: newVarsMuP"
cat /Users/agrummer/Desktop/Bmumu/Bmumu2019/IsoFigures/2020Mar18/v8IsoScripts/newVarCompsMuP/err.txt | grep -e "error" -e "Error" -e "ERROR"
cat /Users/agrummer/Desktop/Bmumu/Bmumu2019/IsoFigures/2020Mar18/v8IsoScripts/newVarCompsMuP/out.txt | grep -e "error" -e "Error" -e "ERROR"

