// Class: ReadBDT
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : BDT::BDT
TMVA Release   : 4.2.1         [262657]
ROOT Release   : 6.10/04       [395780]
Creator        : agrummer
Date           : Mon Feb 26 18:16:43 2018
Host           : Linux lcgapp-slc6-x86-64-3.cern.ch 2.6.32-642.4.2.el6.x86_64 #1 SMP Wed Aug 24 09:19:54 CEST 2016 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /eos/user/a/agrummer/www/bmumu/bsmumu-cbdt
Training events: 986882
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
H: "False" [Print method-specific help message]
NTrees: "50" [Number of trees in the forest]
MaxDepth: "2" [Max depth of the decision tree allowed]
MinNodeSize: "0.2" [Minimum percentage of training events required in a leaf node (default: Classification: 5%, Regression: 0.2%)]
nCuts: "100" [Number of grid points in variable range used in finding optimal cut in node splitting]
BoostType: "AdaBoost" [Boosting type for the trees in the forest (note: AdaCost is still experimental)]
UseBaggedBoost: "True" [Use only a random subsample of all events for growing the trees in each boost iteration.]
AdaBoostBeta: "5.000000e-01" [Learning rate  for AdaBoost algorithm]
BaggedSampleFraction: "6.000000e-01" [Relative size of bagged event sample to original size of the data sample (used whenever bagging is used (i.e. UseBaggedBoost, Bagging,)]
SeparationType: "giniindex" [Separation criterion for node splitting]
DoBoostMonitor: "True" [Create control plot with ROC integral vs tree number]
# Default:
VerbosityLevel: "Default" [Verbosity level]
VarTransform: "None" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
AdaBoostR2Loss: "quadratic" [Type of Loss function in AdaBoostR2]
Shrinkage: "1.000000e+00" [Learning rate for GradBoost algorithm]
UseRandomisedTrees: "False" [Determine at each node splitting the cut variable only as the best out of a random subset of variables (like in RandomForests)]
UseNvars: "4" [Size of the subset of variables used with RandomisedTree option]
UsePoissonNvars: "True" [Interpret "UseNvars" not as fixed number but as mean of a Poisson distribution in each split with RandomisedTree option]
UseYesNoLeaf: "True" [Use Sig or Bkg categories, or the purity=S/(S+B) as classification of the leaf node -> Real-AdaBoost]
NegWeightTreatment: "inverseboostnegweights" [How to treat events with negative weights in the BDT training (particular the boosting) : IgnoreInTraining;  Boost With inverse boostweight; Pair events with negative and positive weights in training sample and *annihilate* them (experimental!)]
Css: "1.000000e+00" [AdaCost: cost of true signal selected signal]
Cts_sb: "1.000000e+00" [AdaCost: cost of true signal selected bkg]
Ctb_ss: "1.000000e+00" [AdaCost: cost of true bkg    selected signal]
Cbb: "1.000000e+00" [AdaCost: cost of true bkg    selected bkg ]
NodePurityLimit: "5.000000e-01" [In boosting/pruning, nodes with purity > NodePurityLimit are signal; background otherwise.]
RegressionLossFunctionBDTG: "huber" [Loss function for BDTG regression.]
HuberQuantile: "7.000000e-01" [In the Huber loss function this is the quantile that separates the core from the tails in the residuals distribution.]
UseFisherCuts: "False" [Use multivariate splits using the Fisher criterion]
MinLinCorrForFisher: "8.000000e-01" [The minimum linear correlation between two variables demanded for use in Fisher criterion in node splitting]
UseExclusiveVars: "False" [Variables already used in fisher criterion are not anymore analysed individually for node splitting]
DoPreselection: "False" [and and apply automatic pre-selection for 100% efficient signal (bkg) cuts prior to training]
SigToBkgFraction: "1.000000e+00" [Sig to Bkg ratio used in Training (similar to NodePurityLimit, which cannot be used in real adaboost]
PruneMethod: "nopruning" [Note: for BDTs use small trees (e.g.MaxDepth=3) and NoPruning:  Pruning: Method used for pruning (removal) of statistically insignificant branches ]
PruneStrength: "0.000000e+00" [Pruning strength]
PruningValFraction: "5.000000e-01" [Fraction of events to use for optimizing automatic pruning.]
SkipNormalization: "False" [Skip normalization at initialization, to keep expectation value of BDT output according to the fraction of events]
nEventsMin: "0" [deprecated: Use MinNodeSize (in % of training events) instead]
UseBaggedGrad: "False" [deprecated: Use *UseBaggedBoost* instead:  Use only a random subsample of all events for growing the trees in each iteration.]
GradBaggingFraction: "6.000000e-01" [deprecated: Use *BaggedSampleFraction* instead: Defines the fraction of events to be used in each iteration, e.g. when UseBaggedGrad=kTRUE. ]
UseNTrainEvents: "0" [deprecated: Use *BaggedSampleFraction* instead: Number of randomly picked training events used in randomised (and bagged) trees]
NNodesMax: "0" [deprecated: Use MaxDepth instead to limit the tree size]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 12
B_pT                          B_pT                          B_pT                          p_{T}^{B}                     MeV                               'F'    [8000.31152344,183548.390625]
Lxy                           Lxy                           Lxy                           L_{xy}                        mm                                'F'    [0.000922113249544,52.8946647644]
TMath::Abs(d0Min_sig)         TMath_Abs_d0Min_sig_          TMath::Abs(d0Min_sig)         |d_{0}|^{min} sig.                                              'F'    [3.17266994898e-07,254.746307373]
TMath::Abs(d0Max_sig)         TMath_Abs_d0Max_sig_          TMath::Abs(d0Max_sig)         |d_{0}|^{max} sig.                                              'F'    [0.00746889226139,401.130371094]
PlngMin2D                     PlngMin2D                     PlngMin2D                     P^{min}_{L}                   MeV                               'F'    [2625.67700195,71899.65625]
chi2_PVSV_log2D               chi2_PVSV_log2D               chi2_PVSV_log2D               Log(#chi^{2}_{xy})                                              'F'    [-9.20831203461,13.2886533737]
TMath::Abs(a_2D)              TMath_Abs_a_2D_               TMath::Abs(a_2D)              |#alpha_{2D}|                 rad                               'F'    [4.1968178266e-07,0.99999755621]
DR                            DR                            DR                            #DeltaR                                                         'F'    [8.67124545039e-05,1.49998378754]
B_iso_7_Chi2_5_LoosePt05      B_iso_7_Chi2_5_LoosePt05      B_iso_7_Chi2_5_LoosePt05      B Isolation (I^{B}_{0.7})                                       'F'    [0.0112288407981,1]
TMath::Abs(B_IDtrks_deltaPhi) TMath_Abs_B_IDtrks_deltaPhi_  TMath::Abs(B_IDtrks_deltaPhi) |#Delta#phi_{#mu#mu}|                                           'F'    [2.34988056036e-06,1.31075084209]
TMath::Abs(B_IDtrks_DCA)      TMath_Abs_B_IDtrks_DCA_       TMath::Abs(B_IDtrks_DCA)      DOCA_{#mu#mu}                 mm                                'F'    [4.77743391514e-08,0.688702881336]
Bvtx3DIP                      Bvtx3DIP                      Bvtx3DIP                      |IP_{B}^{3D}|                                                   'F'    [6.22358566034e-05,8.58981990814]
NSpec 0


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#define NN new BDTNode
   
#ifndef BDTNode__def
#define BDTNode__def
   
class BDTNode {
   
public:
   
   // constructor of an essentially "empty" node floating in space
   BDTNode ( BDTNode* left,BDTNode* right,
                          int selector, double cutValue, bool cutType, 
                          int nodeType, double purity, double response ) :
   fLeft         ( left         ),
   fRight        ( right        ),
   fSelector     ( selector     ),
   fCutValue     ( cutValue     ),
   fCutType      ( cutType      ),
   fNodeType     ( nodeType     ),
   fPurity       ( purity       ),
   fResponse     ( response     ){
   }

   virtual ~BDTNode();

   // test event if it descends the tree at this node to the right
   virtual bool GoesRight( const std::vector<double>& inputValues ) const;
   BDTNode* GetRight( void )  {return fRight; };

   // test event if it descends the tree at this node to the left 
   virtual bool GoesLeft ( const std::vector<double>& inputValues ) const;
   BDTNode* GetLeft( void ) { return fLeft; };   

   // return  S/(S+B) (purity) at this node (from  training)

   double GetPurity( void ) const { return fPurity; } 
   // return the node type
   int    GetNodeType( void ) const { return fNodeType; }
   double GetResponse(void) const {return fResponse;}

private:

   BDTNode*   fLeft;     // pointer to the left daughter node
   BDTNode*   fRight;    // pointer to the right daughter node
   int                     fSelector; // index of variable used in node selection (decision tree)   
   double                  fCutValue; // cut value applied on this node to discriminate bkg against sig
   bool                    fCutType;  // true: if event variable > cutValue ==> signal , false otherwise
   int                     fNodeType; // Type of node: -1 == Bkg-leaf, 1 == Signal-leaf, 0 = internal 
   double                  fPurity;   // Purity of node from training
   double                  fResponse; // Regression response value of node
}; 
   
//_______________________________________________________________________
   BDTNode::~BDTNode()
{
   if (fLeft  != NULL) delete fLeft;
   if (fRight != NULL) delete fRight;
}; 
   
//_______________________________________________________________________
bool BDTNode::GoesRight( const std::vector<double>& inputValues ) const
{
   // test event if it descends the tree at this node to the right
   bool result;
     result = (inputValues[fSelector] > fCutValue );
   if (fCutType == true) return result; //the cuts are selecting Signal ;
   else return !result;
}
   
//_______________________________________________________________________
bool BDTNode::GoesLeft( const std::vector<double>& inputValues ) const
{
   // test event if it descends the tree at this node to the left
   if (!this->GoesRight(inputValues)) return true;
   else return false;
}
   
#endif
   
#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadBDT : public IClassifierReader {

 public:

   // constructor
   ReadBDT( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReadBDT" ),
        fNvars( 12 ),
        fIsNormalised( false )
   {      
      // the training input variables
      const char* inputVars[] = { "B_pT", "Lxy", "TMath::Abs(d0Min_sig)", "TMath::Abs(d0Max_sig)", "PlngMin2D", "chi2_PVSV_log2D", "TMath::Abs(a_2D)", "DR", "B_iso_7_Chi2_5_LoosePt05", "TMath::Abs(B_IDtrks_deltaPhi)", "TMath::Abs(B_IDtrks_DCA)", "Bvtx3DIP" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = 0;
      fVmax[0] = 0;
      fVmin[1] = 0;
      fVmax[1] = 0;
      fVmin[2] = 0;
      fVmax[2] = 0;
      fVmin[3] = 0;
      fVmax[3] = 0;
      fVmin[4] = 0;
      fVmax[4] = 0;
      fVmin[5] = 0;
      fVmax[5] = 0;
      fVmin[6] = 0;
      fVmax[6] = 0;
      fVmin[7] = 0;
      fVmax[7] = 0;
      fVmin[8] = 0;
      fVmax[8] = 0;
      fVmin[9] = 0;
      fVmax[9] = 0;
      fVmin[10] = 0;
      fVmax[10] = 0;
      fVmin[11] = 0;
      fVmax[11] = 0;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';
      fType[4] = 'F';
      fType[5] = 'F';
      fType[6] = 'F';
      fType[7] = 'F';
      fType[8] = 'F';
      fType[9] = 'F';
      fType[10] = 'F';
      fType[11] = 'F';

      // initialize constants
      Initialize();

   }

   // destructor
   virtual ~ReadBDT() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[12];
   double fVmax[12];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[12];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)
   std::vector<BDTNode*> fForest;       // i.e. root nodes of decision trees
   std::vector<double>                fBoostWeights; // the weights applied in the individual boosts
};

double ReadBDT::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   double myMVA = 0;
   double norm  = 0;
   for (unsigned int itree=0; itree<fForest.size(); itree++){
      BDTNode *current = fForest[itree];
      while (current->GetNodeType() == 0) { //intermediate node
         if (current->GoesRight(inputValues)) current=(BDTNode*)current->GetRight();
         else current=(BDTNode*)current->GetLeft();
      }
      myMVA += fBoostWeights[itree] *  current->GetNodeType();
      norm  += fBoostWeights[itree];
   }
   return myMVA /= norm;
};

void ReadBDT::Initialize()
{
  // itree = 0
  fBoostWeights.push_back(0.931182124341208);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.133608, 1, 1, 0.863131,-99) , 
NN(
0, 
0, 
-1, 0.882522, 0, -1, 0.131954,-99) , 
6, 0.0693071, 1, 0, 0.499952,-99)    );
  // itree = 1
  fBoostWeights.push_back(0.743753);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.73127, 0, 1, 0.87715,-99) , 
NN(
0, 
0, 
-1, 0.868214, 0, -1, 0.228086,-99) , 
7, 0.133741, 1, 0, 0.498166,-99)    );
  // itree = 2
  fBoostWeights.push_back(0.79218);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.863848,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.315983,-99) , 
6, 0.198017, 1, 0, 0.755835,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.764143,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.157362,-99) , 
7, 0.0595826, 1, 0, 0.242862,-99) , 
8, 0.823783, 0, 0, 0.525838,-99)    );
  // itree = 3
  fBoostWeights.push_back(0.529956);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.193111, 1, 1, 0.754781,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.642777,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.2362,-99) , 
6, 0.0297023, 1, 0, 0.34084,-99) , 
8, 0.866185, 0, 0, 0.528298,-99)    );
  // itree = 4
  fBoostWeights.push_back(0.486444);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.791957,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.353749,-99) , 
8, 0.731267, 0, 0, 0.701111,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.516289,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.183325,-99) , 
11, 0.0692486, 1, 0, 0.3227,-99) , 
7, 0.207988, 1, 0, 0.508438,-99)    );
  // itree = 5
  fBoostWeights.push_back(0.29446);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.937403,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.390784,-99) , 
5, 3.94412, 0, 0, 0.878261,-99) , 
NN(
0, 
0, 
-1, 0.706306, 0, -1, 0.412603,-99) , 
7, 0.0446381, 1, 0, 0.495105,-99)    );
  // itree = 6
  fBoostWeights.push_back(0.374839);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.737635,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.324648,-99) , 
8, 0.6664, 0, 0, 0.687096,-99) , 
NN(
0, 
0, 
-1, 0.735675, 0, -1, 0.36985,-99) , 
7, 0.207986, 1, 0, 0.525381,-99)    );
  // itree = 7
  fBoostWeights.push_back(0.323957);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 6.37224, 0, 1, 0.63274,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.530634,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.110709,-99) , 
5, 2.66086, 1, 0, 0.326373,-99) , 
6, 0.148513, 1, 0, 0.531963,-99)    );
  // itree = 8
  fBoostWeights.push_back(0.358307);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.0595403, 1, 1, 0.709747,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.744715,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.358888,-99) , 
2, 9.36967, 0, 0, 0.406574,-99) , 
8, 0.911892, 0, 0, 0.504015,-99)    );
  // itree = 9
  fBoostWeights.push_back(0.281186);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.903408,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.406183,-99) , 
1, 0.552191, 0, 0, 0.813393,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.551232,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.32751,-99) , 
10, 0.0539669, 1, 0, 0.460878,-99) , 
7, 0.0446381, 1, 0, 0.51336,-99)    );
  // itree = 10
  fBoostWeights.push_back(0.193192);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.927838,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.452474,-99) , 
1, 0.531555, 0, 0, 0.871597,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.512678,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.232612,-99) , 
8, 0.682325, 0, 0, 0.457665,-99) , 
7, 0.0298274, 1, 0, 0.499947,-99)    );
  // itree = 11
  fBoostWeights.push_back(0.181843);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 4.90319, 0, 1, 0.869588,-99) , 
NN(
0, 
0, 
-1, 0.277226, 1, -1, 0.441058,-99) , 
7, 0.0297876, 1, 0, 0.48381,-99)    );
  // itree = 12
  fBoostWeights.push_back(0.182305);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.915257,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.445328,-99) , 
1, 0.48751, 0, 0, 0.863198,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.51642,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.254379,-99) , 
6, 0.29702, 1, 0, 0.466252,-99) , 
7, 0.0297982, 1, 0, 0.503872,-99)    );
  // itree = 13
  fBoostWeights.push_back(0.212258);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.86406,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.429238,-99) , 
5, 4.26309, 0, 0, 0.783398,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.508135,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.305019,-99) , 
11, 0.085363, 1, 0, 0.438278,-99) , 
7, 0.0446775, 1, 0, 0.48507,-99)    );
  // itree = 14
  fBoostWeights.push_back(0.262792);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.909031,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.494041,-99) , 
1, 0.646141, 0, 0, 0.835604,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.651472,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.400372,-99) , 
8, 0.961494, 0, 0, 0.441329,-99) , 
7, 0.0297876, 1, 0, 0.476301,-99)    );
  // itree = 15
  fBoostWeights.push_back(0.133359);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.805403, 0, 1, 0.767841,-99) , 
NN(
0, 
0, 
-1, 0.608112, 0, -1, 0.463868,-99) , 
7, 0.0446364, 1, 0, 0.503428,-99)    );
  // itree = 16
  fBoostWeights.push_back(0.162491);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.819347,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.425847,-99) , 
6, 0.0396008, 1, 0, 0.714453,-99) , 
NN(
0, 
0, 
-1, 10.1843, 1, -1, 0.464881,-99) , 
2, 6.15092, 0, 0, 0.516672,-99)    );
  // itree = 17
  fBoostWeights.push_back(0.184906);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 4.24815, 0, 1, 0.565974,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.593679,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.146682,-99) , 
5, 1.419, 1, 0, 0.288231,-99) , 
6, 0.356433, 1, 0, 0.531529,-99)    );
  // itree = 18
  fBoostWeights.push_back(0.17067);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.0297876, 1, 1, 0.561225,-99) , 
NN(
0, 
0, 
-1, 0.188117, 1, -1, 0.334273,-99) , 
8, 0.711594, 0, 0, 0.510643,-99)    );
  // itree = 19
  fBoostWeights.push_back(0.118114);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 5.18701, 0, 1, 0.799371,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501658,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.287751,-99) , 
11, 0.136106, 1, 0, 0.464796,-99) , 
7, 0.0297876, 1, 0, 0.491461,-99)    );
  // itree = 20
  fBoostWeights.push_back(0.203436);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.690755,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.0850922,-99) , 
6, 0.108903, 1, 0, 0.639335,-99) , 
NN(
0, 
0, 
-1, 7.03185, 1, -1, 0.433119,-99) , 
2, 5.04449, 0, 0, 0.481398,-99)    );
  // itree = 21
  fBoostWeights.push_back(0.156237);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.0297876, 1, 1, 0.55952,-99) , 
NN(
0, 
0, 
-1, 19213.5, 1, -1, 0.387155,-99) , 
10, 0.0599632, 1, 0, 0.501437,-99)    );
  // itree = 22
  fBoostWeights.push_back(0.148412);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 6.38364, 0, 1, 0.53862,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.524869,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.15336,-99) , 
6, 0.0891101, 1, 0, 0.329744,-99) , 
11, 0.102822, 1, 0, 0.491468,-99)    );
  // itree = 23
  fBoostWeights.push_back(0.200184);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.738412,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.33804,-99) , 
5, 3.62814, 0, 0, 0.622972,-99) , 
NN(
0, 
0, 
-1, 0.0994442, 1, -1, 0.432968,-99) , 
6, 0.0198023, 1, 0, 0.473357,-99)    );
  // itree = 24
  fBoostWeights.push_back(0.0821906);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.0298332, 1, 1, 0.524026,-99) , 
NN(
0, 
0, 
-1, 14773.3, 1, -1, 0.204057,-99) , 
8, 0.560321, 0, 0, 0.504049,-99)    );
  // itree = 25
  fBoostWeights.push_back(0.155877);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.540113,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.342041,-99) , 
11, 0.130887, 1, 0, 0.50913,-99) , 
NN(
0, 
0, 
-1, 13323.8, 1, -1, 0.246326,-99) , 
8, 0.608407, 0, 0, 0.483855,-99)    );
  // itree = 26
  fBoostWeights.push_back(0.150657);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.059531, 1, 1, 0.617195,-99) , 
NN(
0, 
0, 
-1, 0.277228, 1, -1, 0.435887,-99) , 
8, 0.951051, 0, 0, 0.472266,-99)    );
  // itree = 27
  fBoostWeights.push_back(0.184667);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.559505,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.372856,-99) , 
0, 18455.9, 1, 0, 0.515858,-99) , 
NN(
0, 
0, 
-1, 2.41781, 1, -1, 0.315159,-99) , 
6, 0.306926, 1, 0, 0.486582,-99)    );
  // itree = 28
  fBoostWeights.push_back(0.130305);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.773607,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.12144,-99) , 
6, 0.0593939, 1, 0, 0.723121,-99) , 
NN(
0, 
0, 
-1, 0.0750074, 1, -1, 0.452602,-99) , 
2, 13.3015, 0, 0, 0.472676,-99)    );
  // itree = 29
  fBoostWeights.push_back(0.161538);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.582913,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.445875,-99) , 
10, 0.0405099, 1, 0, 0.514256,-99) , 
NN(
0, 
0, 
-1, 0.0123336, 1, -1, 0.189809,-99) , 
8, 0.543637, 0, 0, 0.498706,-99)    );
  // itree = 30
  fBoostWeights.push_back(0.0836776);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.816447, 0, 1, 0.740521,-99) , 
NN(
0, 
0, 
-1, 0.595687, 0, -1, 0.473374,-99) , 
7, 0.0297982, 1, 0, 0.492252,-99)    );
  // itree = 31
  fBoostWeights.push_back(0.16258);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 6.27233, 0, 1, 0.550347,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.548573,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.253405,-99) , 
6, 0.108903, 1, 0, 0.420985,-99) , 
11, 0.0679583, 1, 0, 0.503686,-99)    );
  // itree = 32
  fBoostWeights.push_back(0.0730878);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.862313,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.445916,-99) , 
6, 0.0197994, 1, 0, 0.757156,-99) , 
NN(
0, 
0, 
-1, 0.598618, 0, -1, 0.475783,-99) , 
2, 17.102, 0, 0, 0.48904,-99)    );
  // itree = 33
  fBoostWeights.push_back(0.071488);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.75273,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.498486,-99) , 
7, 0.0297876, 1, 0, 0.515997,-99) , 
NN(
0, 
0, 
-1, 13271.2, 1, -1, 0.276341,-99) , 
8, 0.598618, 0, 0, 0.496262,-99)    );
  // itree = 34
  fBoostWeights.push_back(0.119421);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.0149372, 1, 1, 0.544058,-99) , 
NN(
0, 
0, 
-1, 13708.1, 1, -1, 0.395114,-99) , 
8, 0.735675, 0, 0, 0.506423,-99)    );
  // itree = 35
  fBoostWeights.push_back(0.079109);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 6.36274, 0, 1, 0.523578,-99) , 
NN(
0, 
0, 
-1, 0.198016, 1, -1, 0.369489,-99) , 
11, 0.130922, 1, 0, 0.500674,-99)    );
  // itree = 36
  fBoostWeights.push_back(0.0868667);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.814747,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.187136,-99) , 
6, 0.0494953, 1, 0, 0.76615,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500922,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.344372,-99) , 
11, 0.104263, 1, 0, 0.47026,-99) , 
2, 17.6557, 0, 0, 0.482896,-99)    );
  // itree = 37
  fBoostWeights.push_back(0.147095);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.598473,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.0661401,-99) , 
6, 0.158406, 1, 0, 0.570499,-99) , 
NN(
0, 
0, 
-1, 7.38984, 1, -1, 0.444121,-99) , 
2, 3.78796, 0, 0, 0.480097,-99)    );
  // itree = 38
  fBoostWeights.push_back(0.142734);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.545298,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.334592,-99) , 
0, 25381.3, 1, 0, 0.529829,-99) , 
NN(
0, 
0, 
-1, 0.695133, 0, -1, 0.351786,-99) , 
10, 0.083948, 1, 0, 0.498098,-99)    );
  // itree = 39
  fBoostWeights.push_back(0.119289);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.528854,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.408239,-99) , 
0, 16690.8, 1, 0, 0.495043,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.644351,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.210855,-99) , 
9, 0.0769888, 1, 0, 0.246618,-99) , 
8, 0.559458, 0, 0, 0.481179,-99)    );
  // itree = 40
  fBoostWeights.push_back(0.0793255);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.796665,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.480219,-99) , 
2, 21.2408, 0, 0, 0.489158,-99) , 
NN(
0, 
0, 
-1, 0.108894, 1, -1, 0.256089,-99) , 
8, 0.560321, 0, 0, 0.476253,-99)    );
  // itree = 41
  fBoostWeights.push_back(0.0764318);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.706834,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.489035,-99) , 
7, 0.0298399, 1, 0, 0.502961,-99) , 
NN(
0, 
0, 
-1, 13237.2, 1, -1, 0.308641,-99) , 
8, 0.608407, 0, 0, 0.486001,-99)    );
  // itree = 42
  fBoostWeights.push_back(0.046824);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.733087,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.497065,-99) , 
2, 16.8654, 0, 0, 0.507128,-99) , 
NN(
0, 
0, 
-1, 0.164442, 1, -1, 0.292838,-99) , 
8, 0.559458, 0, 0, 0.495392,-99)    );
  // itree = 43
  fBoostWeights.push_back(0.0392862);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.0149475, 1, 1, 0.511042,-99) , 
NN(
0, 
0, 
-1, 0.274749, 1, -1, 0.210555,-99) , 
8, 0.509048, 0, 0, 0.501769,-99)    );
  // itree = 44
  fBoostWeights.push_back(0.0550553);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.014937, 1, 1, 0.513138,-99) , 
NN(
0, 
0, 
-1, 13323.8, 1, -1, 0.294695,-99) , 
8, 0.59523, 0, 0, 0.496811,-99)    );
  // itree = 45
  fBoostWeights.push_back(0.144636);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.0198005, 1, 1, 0.580137,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.544821,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.41542,-99) , 
0, 12429.7, 1, 0, 0.464677,-99) , 
8, 0.942241, 0, 0, 0.490299,-99)    );
  // itree = 46
  fBoostWeights.push_back(0.0629392);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 1.61268, 0, 1, 0.808223,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500007,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.376864,-99) , 
11, 0.107971, 1, 0, 0.475958,-99) , 
7, 0.0149478, 1, 0, 0.484581,-99)    );
  // itree = 47
  fBoostWeights.push_back(0.0926121);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.801499,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.493624,-99) , 
2, 22.7002, 0, 0, 0.502548,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.547602,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.141603,-99) , 
5, 2.18191, 1, 0, 0.369445,-99) , 
6, 0.247525, 1, 0, 0.477948,-99)    );
  // itree = 48
  fBoostWeights.push_back(0.0877651);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.523446,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.236722,-99) , 
8, 0.510509, 0, 0, 0.515021,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.516498,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.128183,-99) , 
5, 1.92019, 1, 0, 0.330018,-99) , 
6, 0.425742, 1, 0, 0.49934,-99)    );
  // itree = 49
  fBoostWeights.push_back(0.130258);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.537491,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.400589,-99) , 
5, 1.54788, 0, 0, 0.513556,-99) , 
NN(
0, 
0, 
-1, 2.81293, 1, -1, 0.34162,-99) , 
6, 0.287128, 1, 0, 0.487864,-99)    );
   return;
};
 
// Clean up
inline void ReadBDT::Clear() 
{
   for (unsigned int itree=0; itree<fForest.size(); itree++) { 
      delete fForest[itree]; 
   }
}
   inline double ReadBDT::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            iV.reserve(inputValues.size());
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            retval = GetMvaValue__( iV );
         }
         else {
            retval = GetMvaValue__( inputValues );
         }
      }

      return retval;
   }
